

services:
  backend:
    build: .
    container_name: Baby-Monitor-Backend
    ports:
      - "8080:8080"
    networks:
      - shared

networks:
  shared:
    external: true
    name: shared-app-network